### ISSUE TITLE
malloc: attempt to free non-allocated memory (uninitialized/freed pointer/NULL) 

### ISSUE THREAD

**Issue by jonand** [dvorka/hstr#353]
Whenever I use `hstr` I get the following errors:
```
$ hstr
ls
hstr(45522,0x1142ce5c0) malloc: *** error for object 0x7fccffe4f40f: pointer being freed was not allocated
hstr(45522,0x1142ce5c0) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    45522 abort      hstr
$ ls
```
It doesn't matter if I trigger it with `hstr`, `hh` or `^R`, I always get the malloc errors. `hstr` still works, but always prints the errors
I recently re-installed my machine from scratch but the problem persists.

My config:
- macOS Mojave v10.14.5
- zsh 5.7.1 (x86_64-apple-darwin18.2.0)
```
alias hh=hstr                                # hh to be alias for hstr
export HISTFILE=~/.zhistory                  # ensure history file visibility
export HISTFILESIZE=100000                   # increase history file size
export HISTSIZE=${HISTFILESIZE}
export HSTR_CONFIG=hicolor,raw-history-view,blacklist
bindkey -s "\C-r" "\eqhstr\n"                # bind hh to Ctrl-r
```

**Comment by dvorka** [comment]
@jonand @arnas-teso @mvilanova or anybody else who can reproduce this problem, can you please share HSTR version impacted by this problem please? HSTR 2.0 was released with all memory leaks/invalid memory use fixed AFAIK. Thanks!

**Comment by arnaspet** [comment]
```
➜ hstr
git status
hstr(40422,0x10a0515c0) malloc: *** error for object 0x7ffdc7c8617f: pointer being freed was not allocated
hstr(40422,0x10a0515c0) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    40422 abort      hstr

➜ hstr --version
hstr version "2.0.0" (2018-08-28T13:30:00)

```

tried upgrading with brew, but brew sees only 2.0.1 version
`Warning: hstr 2.0_1 already installed`

**Comment by mvilanova** [comment]
Running hstr version "2.0.0" (2018-08-28T13:30:00) in zsh 5.7.1
(x86_64-apple-darwin19.0) on macOS Catalina (10.15.1).

 mvilanova ~ hstr
echo "hello"
hstr(15000,0x111e0fdc0) malloc: *** error for object 0x7faea65cac6f:
pointer being freed was not allocated
hstr(15000,0x111e0fdc0) malloc: *** set a breakpoint in malloc_error_break
to debug
[1]    15000 abort      hstr
 mvilanova ~ echo "hello"
hello

Marc

**Comment by dvorka** [comment]
@mvilanova @arnaspet thank you for quick response, it helps - I really appreciate it! :+1:

**Comment by dvorka** [comment]
@mvilanova @arnaspet I just fixed a few HSTR leaks, but most probably not the one causing crash reported in this issue. It seems to be caused by freeing non-initialized/NULL pointer, but unfortunately it's not reproducible on my systems (Linux @ zsh / bash). Can you please run the following command for me and share `hstr-log.txt` file here?
```
valgrind --track-origins=yes --tool=memcheck --leak-check=full --show-leak-kinds=all ./hstr 2> hstr-log.txt
```

**Comment by dvorka** [comment]
It might be fixed by e9452d2 released as HSTR `2.2`, please verify.

**Comment by mvilanova** [comment]
Not seeing this version in brew yet.

Marc

**Comment by jonand** [comment]
Now 2.2 is available via brew. I installed it but I'm still seeing the malloc errors.

Unfortunately there's no `strace` for macOS and `valgrind` doesn't seem to work with macOS Catalina yet. Maybe this `dtruss` output helps?
```sudo dtruss hstr -n &> hstr-log-dtruss.txt```
[hstr-log-dtruss.txt](https://github.com/dvorka/hstr/files/4030388/hstr-log-dtruss.txt)

**Comment by dvorka** [comment]
:disappointed: thank you@jonand. I will set up macOS installation when I will be releasing my other project and try to debug it there. Thanks for patience & help!

**Comment by ostrolucky** [comment]
Any news about this? I have same problem

```
❯ zsh --version                                                                                                                                                                                                                     
zsh 5.7.1 (x86_64-apple-darwin19.0)
❯ hstr --version
hstr version "2.2.0" (2019-12-21T08:47:00)
❯ hstr
hstr(42631,0x1133c0dc0) malloc: *** error for object 0x7fc9904164cf: pointer being freed was not allocated
hstr(42631,0x1133c0dc0) malloc: *** set a breakpoint in malloc_error_break to debug
[1]    42631 abort      hstr
❯
```

**Comment by ostrolucky** [comment]
I was able to solve this issue by downgrading to hstr 2.0 (2.1, 2.2 have this problem in my testing)

**Comment by michael-wojcik** [comment]
I'm still seeing this same issue with 2.2 on Mac OS Catalina

**Comment by ostrolucky** [comment]
This is the commit that introduced this error https://github.com/dvorka/hstr/commit/c36754179965d09b83d72f0bd575a08919208bf5 Any C developers that can spot what's wrong with it?

**Comment by thibaultcha** [comment]
Could be fixed by #410 as well. If you are experiencing this, are you using zsh by chance? Do any of the commands in your shell's history start with a colon :?

**Comment by ostrolucky** [comment]
I think you nailed it. I use zsh and there is indeed command in my history starting with `:`.

**Comment by dvorka** [comment]
Fixed by https://github.com/dvorka/hstr/pull/410 thanks to joint work of @thibaultcha and @ostrolucky :muscle: Thank you both!
